
# 所使用的数据库映射框架 目前只支持mybatis
orm: mybatis

type: admin
# 配置数据库链接

# 具体的代码生成配置
codeGen:
  iserivce:
    enable: true
    packName:
    needMethod:
      - list:
          ormMethod: "com.zjhc.system.mapper"
      - update
      - delete
      - insert
  serviceimpl:
    packName:


config:
  service: true
  controller: true
  method:
    - query
    - export
    - add
    - update
    - delete



